### ISSUE TITLE
does not support comparison of ObjectId

### ISSUE THREAD

**Issue by stalniy** [crcn/sift.js#158]
`sift@7.x` supported comparison of `ObjectId` values, so this example worked:

```js
function ObjectId(value) { // primitive implementation
  return { 
    toJSON: () => value 
  }
}

const test1 = sift({ 
  $in: [ObjectId('1'), ObjectId('2')]
})

test1(ObjectId('1')) // expects to be true
```

In 8.x it returns `false`, is it expected?

**Comment by crcn** [comment]
This should be fixed now in `8.5.1`. 🙂

**Comment by stalniy** [comment]
@crcn no it's not fixed. Please consider this case (https://repl.it/@stalniy/sift8-error):

```js
const object = { creator: ObjectId('1') }
const test = sift({ creator: ObjectId('1') }

test(object) // false, expects to receive true!
```

Please reopen the issue

**Comment by crcn** [comment]
@stalniy  I added a fix under `9.0.0` (basically just adding this: https://github.com/crcn/sift.js/commit/b3df40b3c69f56a019c318bf858fffb10d01573b#diff-6d186b954a58d5bb740f73d84fe39073R565). Let me know if your issue is fixed.

**Comment by stalniy** [comment]
Everything workds good right now! Thanks for the fix @crcn
