### ISSUE TITLE
v9 doesn't work in IE 11

### ISSUE THREAD

**Issue by raduflp** [crcn/sift.js#172]
originally opened here stalniy/casl#250
`sift@9.0.0` is broken in IE 11 due to the arrow function notations not being supported
looks like this happened here c141e996fe553696820649b510e223fe534a2594
fixing the current issues should be pretty easy, but the bigger questions is: do you intend to support IE11 going forward?

**Comment by crcn** [comment]
Thanks! Just published this to NPM as `9.0.6`.

**Comment by eugene1g** [comment]
Should be resolved with https://github.com/crcn/sift.js/pull/171

**Comment by raduflp** [comment]
the sift@9.06 release is still broken in IE due to syntax
```
$eq: function(n, t, { comparable: r, compare: e }) { 
...
```

@crcn can you make another release with the changes from your last commit?

**Comment by crcn** [comment]
Odd, I'm assuming that `src/index.js` is being loaded in IE 11 which is the incorrect module, it should be `lib/index.js`. I've updated all module paths in`package.json` to point to `lib/index.js`, let me know if that fixes the issue. The fix has been published to NPM as `9.0.7`.

**Comment by raduflp** [comment]
IE is happy with the `9.0.7` release. Thanks the the swift response
